# Generated by Django 5.1.6 on 2025-02-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CForm', '0003_delete_messagetemplate'),
        ('MessageForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.ManyToManyField(related_name='messages', to='CForm.client')),
                ('message_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MessageForm.messagetemplate')),
            ],
        ),
    ]
