# Generated by Django 5.1.6 on 2025-03-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_messages_message_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message_date',
            new_name='message_recorded',
        ),
    ]
