# Generated by Django 5.1.6 on 2025-03-16 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_rename_message_date_messages_message_recorded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='message_recorded',
        ),
        migrations.AddField(
            model_name='messages',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
