# Generated by Django 5.1.6 on 2025-03-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0006_remove_messages_message_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_sid',
            field=models.CharField(max_length=150, null='Undefined.'),
            preserve_default='Undefined.',
        ),
    ]
