# Generated by Django 5.1.6 on 2025-02-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateField(),
        ),
    ]
