# Generated by Django 5.1.6 on 2025-02-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CForm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
    ]
