# Generated by Django 5.1.6 on 2025-02-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CForm', '0002_messagetemplate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
    ]
